Repository oruga-ui/oruga, pull requests merged in 2024-04, with the labels that each got.

#879 fix(step|tab): make item props reactive again
  packages/oruga/src/components/steps/StepItem.vue
  packages/oruga/src/components/tabs/TabItem.vue
Labels: bug

#878 fix(table): make `TableColumn` props reactive again
  packages/oruga/src/components/table/TableColumn.vue
Labels: bug

#888 feat(taginput): add removeItem as selected slot property (#887)
  packages/docs/.vitepress/theme/examples/taginput/custom-selected.vue
  packages/oruga/src/components/taginput/Taginput.vue
Labels: enhancement

#895 feat(taginput): update prop types of `maxlength` and `maxitems`
  packages/docs/components/Autocomplete.md
  packages/docs/components/Taginput.md
  packages/oruga/src/components/autocomplete/Autocomplete.vue
  packages/oruga/src/components/taginput/Taginput.vue
Labels: enhancement

#896 chore: update dependencies
  package-lock.json
  packages/oruga/package.json
  packages/oruga/tsconfig.json
Labels: dependencies

#897 fix(menu): fix `useProviderParent` composable `childItems` type problem
  packages/oruga/src/components/menu/Menu.vue
  packages/oruga/src/composables/useParentProvider.ts
Labels: bug

#882 fix(datepicker): make date parsing work again
  packages/oruga/src/components/datepicker/Datepicker.vue
  packages/oruga/src/components/datepicker/tests/datepicker.test.ts
Labels: bug

#901 feat(datepicker): update readonly default to `false` & disable calendar…
  packages/docs/components/Datepicker.md
  packages/oruga/src/components/datepicker/Datepicker.vue
  packages/oruga/src/components/datepicker/DatepickerMonth.vue
  packages/oruga/src/components/datepicker/DatepickerTableRow.vue
  packages/oruga/src/utils/helpers.ts
Labels: enhancement

#902 fix(field): add field `setInputId` & remove `ariaLabelledby` prop
  packages/docs/components/Checkbox.md
  packages/docs/components/Input.md
  packages/docs/components/Radio.md
  packages/docs/components/Select.md
  packages/docs/components/Switch.md
  packages/docs/components/Upload.md
  packages/oruga/src/components/checkbox/Checkbox.vue
  packages/oruga/src/components/field/Field.vue
  packages/oruga/src/components/field/FieldBody.vue
  packages/oruga/src/components/field/fieldInjection.ts
  packages/oruga/src/components/input/Input.vue
  packages/oruga/src/components/input/tests/__snapshots__/input.test.ts.snap
  packages/oruga/src/components/radio/Radio.vue
  packages/oruga/src/components/select/Select.vue
  packages/oruga/src/components/switch/Switch.vue
  packages/oruga/src/components/upload/Upload.vue
  packages/oruga/src/composables/useInputHandler.ts
  packages/oruga/src/composables/useParentProvider.ts
Labels: bug, a11y

#906 fix(field): fix slot invoked outside render function
  packages/docs/components/Field.md
  packages/oruga/src/components/field/Field.vue
  packages/oruga/src/components/field/FieldBody.vue
  packages/oruga/src/components/field/examples/index.vue
  packages/oruga/src/components/field/fieldInjection.ts
  packages/oruga/src/utils/helpers.ts
Labels: bug, enhancement, refactoring

#908 test(field): add field tests
  packages/oruga/src/components/field/Field.vue
  packages/oruga/src/components/field/tests/__snapshots__/field.test.ts.snap
  packages/oruga/src/components/field/tests/field.test.ts
Labels: enhancement

#911 fix(table): fix filtering when table is not sorted
  packages/oruga/src/components/table/Table.vue
Labels: bug, enhancement

#912 fix(table): debounce function not called
  packages/docs/components/Table.md
  packages/oruga/src/components/table/Table.vue
  packages/oruga/src/components/types.ts
Labels: bug, enhancement
