Repository oruga-ui/oruga, pull requests merged in 2024-06, with the labels that each got.

#937 feat(modal): set default `destroyOnHide` to `true` for programmatic usage
  packages/docs/components/Modal.md
  packages/docs/components/Table.md
  packages/oruga/src/components/modal/Modal.vue
  packages/oruga/src/components/modal/ModalProgrammatic.ts
Labels: enhancement

#927 fix: always validate programmatic date updates for picker components
  packages/oruga/src/components/utils/PickerWrapper.vue
Labels: enhancement

#941 fix(datepicker): update focused date on editing directly
  packages/docs/components/Datepicker.md
  packages/oruga/src/components/datepicker/Datepicker.vue
  packages/oruga/src/components/datepicker/useDatepickerMixins.ts
  packages/oruga/src/components/datetimepicker/examples/base.vue
  packages/oruga/src/components/datetimepicker/examples/footer-slot.vue
  packages/oruga/src/components/utils/PickerWrapper.vue
Labels: bug, enhancement

#930 feat(inputs): detect constraint validation attribute changes
  packages/oruga/src/composables/useInputHandler.ts
Labels: enhancement

#942 fix(taginput): solve defineModel macro array constrains
  packages/oruga/src/components/taginput/Taginput.vue
Labels: bug

#833 refactor(programmatic): cleanup `useProgrammatic` composable
  packages/docs/components/Loading.md
  packages/docs/components/Modal.md
  packages/docs/components/Notification.md
  packages/docs/components/Sidebar.md
  packages/oruga/src/components/dropdown/Dropdown.vue
  packages/oruga/src/components/loading/Loading.vue
  packages/oruga/src/components/loading/examples/programmatically.vue
  packages/oruga/src/components/menu/tests/__snapshots__/menu.test.ts.snap
  packages/oruga/src/components/modal/Modal.vue
  packages/oruga/src/components/notification/Notification.vue
  packages/oruga/src/components/notification/NotificationNotice.vue
  packages/oruga/src/components/notification/NotificationProgrammatic.ts
  packages/oruga/src/components/sidebar/Sidebar.vue
  packages/oruga/src/components/sidebar/SidebarProgrammatic.ts
  packages/oruga/src/components/tooltip/Tooltip.vue
  packages/oruga/src/components/types.ts
  packages/oruga/src/composables/useClickOutside.ts
  packages/oruga/src/composables/useEventListener.ts
  packages/oruga/src/composables/useProgrammatic.ts
Labels: breaking, refactoring

#760 feat(themes): remove theme config function `props` object encapsulation
  packages/oruga/src/composables/defineClasses.ts
Labels: enhancement, breaking

#873 feat: remove deprecated ConfigPlugin export
  packages/oruga/src/index.ts
Labels: breaking, refactoring

#946 feat(table): enhance loading spinner
  packages/docs/components/Table.md
  packages/oruga/src/components/table/Table.vue
  packages/oruga/src/components/types.ts
Labels: enhancement

#947 feat(table): add `before` and `after` slot | add column `display` prop
  packages/docs/components/Table.md
  packages/oruga/src/components/table/Table.vue
  packages/oruga/src/components/table/TableColumn.vue
Labels: enhancement

#919 feat(table): enhance table with generics
  packages/docs/components/Pagination.md
  packages/docs/components/Table.md
  packages/oruga/src/components/pagination/Pagination.vue
  packages/oruga/src/components/table/Table.vue
  packages/oruga/src/components/table/TableColumn.vue
  packages/oruga/src/components/table/TableMobileSort.vue
  packages/oruga/src/components/table/TablePagination.vue
  packages/oruga/src/components/table/examples/async-data.vue
  packages/oruga/src/components/table/examples/base.vue
  packages/oruga/src/components/table/examples/checkable.vue
  packages/oruga/src/components/table/examples/column-prop.vue
  packages/oruga/src/components/table/examples/customise.vue
  packages/oruga/src/components/table/examples/detailed.vue
  packages/oruga/src/components/table/examples/draggable.vue
  packages/oruga/src/components/table/examples/index.vue
  packages/oruga/src/components/table/examples/inspector.vue
  packages/oruga/src/components/table/examples/pagination.vue
  packages/oruga/src/components/table/examples/searchable.vue
  packages/oruga/src/components/table/examples/selection.vue
  packages/oruga/src/components/table/examples/sticky.vue
  packages/oruga/src/components/table/index.ts
  packages/oruga/src/components/table/types.ts
  packages/oruga/src/components/types.ts
  packages/oruga/src/composables/index.ts
  packages/oruga/src/composables/useObjectMap.ts
  packages/oruga/src/utils/helpers.ts
Labels: enhancement, breaking

#949 fix(table): solve searchable filter bug
  packages/oruga/src/components/table/Table.vue
Labels: bug

#909 refactor: replace custom `usePropBinding` composable with `defineModel` macro
  packages/oruga/src/components/carousel/Carousel.vue
  packages/oruga/src/components/checkbox/Checkbox.vue
  packages/oruga/src/components/collapse/Collapse.vue
  packages/oruga/src/components/loading/Loading.vue
  packages/oruga/src/components/notification/Notification.vue
  packages/oruga/src/components/pagination/Pagination.vue
  packages/oruga/src/components/radio/Radio.vue
  packages/oruga/src/components/select/Select.vue
  packages/oruga/src/components/switch/Switch.vue
  packages/oruga/src/components/tooltip/Tooltip.vue
  packages/oruga/src/composables/index.ts
  packages/oruga/src/composables/usePropValue.ts
Labels: refactoring

#914 feat(field): set prop `addons` default to `false`
  packages/docs/components/Field.md
  packages/oruga/src/components/field/Field.vue
  packages/oruga/src/components/field/examples/addons.vue
Labels: enhancement, breaking

#884 feat(input): add `number` prop for vmodel casting
  packages/docs/components/Autocomplete.md
  packages/docs/components/Icon.md
  packages/docs/components/Input.md
  packages/docs/components/Table.md
  packages/docs/docgen.config.js
  packages/oruga/src/components/autocomplete/Autocomplete.vue
  packages/oruga/src/components/datetimepicker/Datetimepicker.vue
  packages/oruga/src/components/input/Input.vue
  packages/oruga/src/components/input/examples/base.vue
  packages/oruga/src/components/utils/PickerWrapper.vue
Labels: enhancement

#955 docs: update the themes (remove oruga-base theme)
  package-lock.json
  packages/docs/.vitepress/themes.json
  packages/docs/components/Autocomplete.md
  packages/docs/components/Button.md
  packages/docs/components/Carousel.md
  packages/docs/components/Checkbox.md
  packages/docs/components/Collapse.md
  packages/docs/components/Datepicker.md
  packages/docs/components/Datetimepicker.md
  packages/docs/components/Dropdown.md
  packages/docs/components/Field.md
  packages/docs/components/Icon.md
  packages/docs/components/Input.md
  packages/docs/components/Loading.md
  packages/docs/components/Menu.md
  packages/docs/components/Modal.md
  packages/docs/components/Notification.md
  packages/docs/components/Pagination.md
  packages/docs/components/Radio.md
  packages/docs/components/Select.md
  packages/docs/components/Sidebar.md
  packages/docs/components/Skeleton.md
  packages/docs/components/Slider.md
  packages/docs/components/Steps.md
  packages/docs/components/Switch.md
  packages/docs/components/Table.md
  packages/docs/components/Tabs.md
  packages/docs/components/Taginput.md
  packages/docs/components/Timepicker.md
  packages/docs/components/Tooltip.md
  packages/docs/components/Upload.md
  packages/docs/documentation/index.md
  packages/docs/documentation/themes.md
  packages/docs/package.json
  packages/docs/themes/theme-oruga.md
  packages/docs/themes/theme-orugafull.md
Labels: documentation

#956 feat(autocomplete|taginput): update component generics and props
  packages/docs/components/Autocomplete.md
  packages/docs/components/Datepicker.md
  packages/docs/components/Datetimepicker.md
  packages/docs/components/Dropdown.md
  packages/docs/components/Input.md
  packages/docs/components/Loading.md
  packages/docs/components/Menu.md
  packages/docs/components/Pagination.md
  packages/docs/components/Sidebar.md
  packages/docs/components/Table.md
  packages/docs/components/Taginput.md
  packages/oruga/src/components/autocomplete/Autocomplete.vue
  packages/oruga/src/components/autocomplete/examples/base.vue
  packages/oruga/src/components/autocomplete/examples/groups.vue
  packages/oruga/src/components/autocomplete/examples/infinite-scroll.vue
  packages/oruga/src/components/autocomplete/examples/inspector.vue
  packages/oruga/src/components/autocomplete/examples/objects-array.vue
  packages/oruga/src/components/datepicker/Datepicker.vue
  packages/oruga/src/components/datetimepicker/Datetimepicker.vue
  packages/oruga/src/components/dropdown/Dropdown.vue
  packages/oruga/src/components/input/Input.vue
  packages/oruga/src/components/input/tests/input.test.ts
  packages/oruga/src/components/loading/Loading.vue
  packages/oruga/src/components/menu/MenuItem.vue
  packages/oruga/src/components/pagination/Pagination.vue
  packages/oruga/src/components/sidebar/Sidebar.vue
  packages/oruga/src/components/table/Table.vue
  packages/oruga/src/components/table/TableColumn.vue
  packages/oruga/src/components/taginput/Taginput.vue
  packages/oruga/src/components/taginput/examples/autocomplete.vue
  packages/oruga/src/components/taginput/examples/base.vue
  packages/oruga/src/components/taginput/tests/__snapshots__/taginput.test.ts.snap
  packages/oruga/src/components/types.ts
  packages/oruga/src/composables/useDebounce.ts
  packages/oruga/src/utils/helpers.ts
Labels: enhancement, breaking, refactoring

#957 feat: expose value for every HTML input based component
  packages/oruga/src/components/autocomplete/Autocomplete.vue
  packages/oruga/src/components/checkbox/Checkbox.vue
  packages/oruga/src/components/datepicker/Datepicker.vue
  packages/oruga/src/components/datetimepicker/Datetimepicker.vue
  packages/oruga/src/components/input/Input.vue
  packages/oruga/src/components/radio/Radio.vue
  packages/oruga/src/components/select/Select.vue
  packages/oruga/src/components/slider/Slider.vue
  packages/oruga/src/components/switch/Switch.vue
  packages/oruga/src/components/taginput/Taginput.vue
  packages/oruga/src/components/timepicker/Timepicker.vue
  packages/oruga/src/components/upload/Upload.vue
  packages/oruga/src/composables/useInputHandler.ts
Labels: enhancement

#958 feat(table): update `thAttrs` and `tdAttrs` property
  packages/docs/components/Table.md
  packages/oruga/src/components/pagination/Pagination.vue
  packages/oruga/src/components/pagination/PaginationButton.vue
  packages/oruga/src/components/pagination/tests/__snapshots__/pagination.test.ts.snap
  packages/oruga/src/components/table/Table.vue
  packages/oruga/src/components/table/TableColumn.vue
  packages/oruga/src/components/table/examples/sticky.vue
  packages/oruga/src/components/table/tests/tablecolumn.test.ts
Labels: bug, enhancement

#948 fix(datetimepicker): fix datetimepicker initialisation bug
  packages/oruga/src/components/datetimepicker/Datetimepicker.vue
Labels: bug

#959 feat(table): expose `sort` function
  packages/docs/components/Table.md
  packages/oruga/src/components/table/Table.vue
  packages/oruga/src/components/table/examples/async-data.vue
  packages/oruga/src/components/table/examples/customise.vue
  packages/oruga/src/components/table/examples/index.vue
  packages/oruga/src/components/table/examples/pagination.vue
  packages/oruga/src/components/types.ts
Labels: enhancement

#960 feat(reactivity): add component class props reactivity
  packages/oruga/src/composables/defineClasses.ts
Labels: feature

#965 refactor(timepicker): adjust select component options
  packages/oruga/src/components/timepicker/Timepicker.vue
Labels: refactoring

#966 feat(select): register id to field wrapper
  packages/oruga/src/components/select/Select.vue
  packages/oruga/src/composables/useInputHandler.ts
Labels: enhancement

#969 feat(radio): add type generics
  packages/oruga/src/components/radio/Radio.vue
Labels: enhancement

#970 test(checkbox): add checkbox tests
  packages/docs/components/Checkbox.md
  packages/oruga/src/components/checkbox/Checkbox.vue
  packages/oruga/src/components/checkbox/tests/Checkbox.spec.cy.ts
  packages/oruga/src/components/checkbox/tests/checkbox.test.ts
Labels: enhancement

#971 feat(select): add native `required` prop
  packages/docs/components/Select.md
  packages/oruga/src/components/select/Select.vue
  packages/oruga/src/components/select/tests/select.test.ts
Labels: enhancement

#972 test(radio): add radio tests
  packages/docs/components/Radio.md
  packages/oruga/src/components/radio/Radio.vue
  packages/oruga/src/components/radio/tests/radio.test.ts
Labels: enhancement

#973 feat(switch): add type generics
  packages/docs/components/Switch.md
  packages/oruga/src/components/switch/Switch.vue
Labels: enhancement

#977 feat(steps): add component generics
  packages/docs/components/Steps.md
  packages/oruga/src/components/steps/StepItem.vue
  packages/oruga/src/components/steps/Steps.vue
  packages/oruga/src/components/steps/types.ts
Labels: enhancement

#978 feat(tabs): add component generics
  packages/docs/components/Tabs.md
  packages/oruga/src/components/tabs/TabItem.vue
  packages/oruga/src/components/tabs/Tabs.vue
  packages/oruga/src/components/tabs/types.ts
Labels: enhancement

#975 test(switch): add switch tests
  packages/oruga/src/components/checkbox/tests/checkbox.test.ts
  packages/oruga/src/components/input/Input.vue
  packages/oruga/src/components/input/tests/input.test.ts
  packages/oruga/src/components/radio/tests/radio.test.ts
  packages/oruga/src/components/switch/tests/switch.test.ts
Labels: enhancement

#979 doc(datepicker): enhance datepicker documentation
  packages/docs/components/Datepicker.md
  packages/oruga/src/components/datepicker/Datepicker.vue
  packages/oruga/src/components/datepicker/examples/base.vue
  packages/oruga/src/components/datepicker/examples/programmatically.vue
Labels: documentation, enhancement

#981 fix: adjust exposed `value` prop
  packages/oruga/src/components/datepicker/Datepicker.vue
  packages/oruga/src/components/datetimepicker/Datetimepicker.vue
  packages/oruga/src/components/timepicker/Timepicker.vue
Labels: bug

#982 feat(upload): add component generics
  packages/docs/components/Upload.md
  packages/oruga/src/components/upload/Upload.vue
Labels: enhancement

#983 refactor(slider): adjust slider implementation
  packages/docs/components/Slider.md
  packages/oruga/src/components/slider/Slider.vue
Labels: refactoring

#980 docs: enahnce type documentation
  packages/docs/components/Autocomplete.md
  packages/docs/components/Carousel.md
  packages/docs/components/Checkbox.md
  packages/docs/components/Radio.md
  packages/docs/components/Select.md
  packages/docs/components/Switch.md
  packages/docs/components/Table.md
  packages/docs/components/Tabs.md
  packages/docs/components/Taginput.md
  packages/oruga/src/components/autocomplete/Autocomplete.vue
  packages/oruga/src/components/autocomplete/examples/groups.vue
  packages/oruga/src/components/carousel/Carousel.vue
  packages/oruga/src/components/checkbox/Checkbox.vue
  packages/oruga/src/components/radio/Radio.vue
  packages/oruga/src/components/select/Select.vue
  packages/oruga/src/components/slider/examples/range.vue
  packages/oruga/src/components/steps/StepItem.vue
  packages/oruga/src/components/switch/Switch.vue
  packages/oruga/src/components/table/Table.vue
  packages/oruga/src/components/tabs/TabItem.vue
  packages/oruga/src/components/taginput/Taginput.vue
Labels: documentation, enhancement

#988 docs(gen): use `vue-component-meta` while docgen generation
  package-lock.json
  packages/docs/components/Autocomplete.md
  packages/docs/components/Carousel.md
  packages/docs/components/Checkbox.md
  packages/docs/components/Collapse.md
  packages/docs/components/Datepicker.md
  packages/docs/components/Datetimepicker.md
  packages/docs/components/Dropdown.md
  packages/docs/components/Icon.md
  packages/docs/components/Input.md
  packages/docs/components/Loading.md
  packages/docs/components/Modal.md
  packages/docs/components/Pagination.md
  packages/docs/components/Radio.md
  packages/docs/components/Select.md
  packages/docs/components/Sidebar.md
  packages/docs/components/Skeleton.md
  packages/docs/components/Slider.md
  packages/docs/components/Steps.md
  packages/docs/components/Switch.md
  packages/docs/components/Table.md
  packages/docs/components/Tabs.md
  packages/docs/components/Taginput.md
  packages/docs/components/Timepicker.md
  packages/docs/components/Tooltip.md
  packages/docs/components/Upload.md
  packages/docs/docgen.config.js
  packages/docs/package.json
  packages/oruga/src/components/autocomplete/Autocomplete.vue
  packages/oruga/src/components/carousel/Carousel.vue
  packages/oruga/src/components/checkbox/Checkbox.vue
  packages/oruga/src/components/datepicker/Datepicker.vue
  packages/oruga/src/components/datetimepicker/Datetimepicker.vue
  packages/oruga/src/components/dropdown/Dropdown.vue
  packages/oruga/src/components/input/Input.vue
  packages/oruga/src/components/radio/Radio.vue
  packages/oruga/src/components/select/Select.vue
  packages/oruga/src/components/slider/Slider.vue
  packages/oruga/src/components/steps/Steps.vue
  packages/oruga/src/components/switch/Switch.vue
  packages/oruga/src/components/tabs/Tabs.vue
  packages/oruga/src/components/taginput/Taginput.vue
  packages/oruga/src/components/timepicker/Timepicker.vue
  packages/oruga/src/components/upload/Upload.vue
Labels: documentation, enhancement

#990 fix(types): add lookup replacement to component type generation script
  .scripts/gen-comp-types.mjs
Labels: bug

#989 build(dependency): update dependencies
  package-lock.json
  packages/docs/components/Collapse.md
  packages/docs/components/Dropdown.md
  packages/docs/components/Sidebar.md
  packages/docs/components/Steps.md
  packages/docs/components/Tabs.md
  packages/docs/docgen.config.js
  packages/docs/package.json
  packages/oruga/package.json
Labels: dependencies

#964 fix(select): adjust placeholder behavior
  packages/docs/components/Select.md
  packages/oruga/src/components/datetimepicker/tests/__snapshots__/datetimepicker.test.ts.snap
  packages/oruga/src/components/select/Select.vue
  packages/oruga/src/components/timepicker/tests/__snapshots__/timepicker.test.ts.snap
Labels: bug

#986 fix(picker): fix native input value
  .github/workflows/build.yml
  packages/oruga/src/components/datepicker/Datepicker.vue
  packages/oruga/src/components/timepicker/Timepicker.vue
  packages/oruga/src/components/utils/PickerWrapper.vue
  packages/oruga/src/composables/useInputHandler.ts
Labels: bug
