Repository oruga-ui/oruga, pull requests merged in 2024-02, with the labels that each got.

#756 fix(notification): adjust querySelector
  packages/oruga-next/src/components/notification/NotificationNotice.vue
Labels: bug

#757 fix(carousel): fix repeat index
  packages/oruga-next/src/components/carousel/Carousel.vue
Labels: bug

#725 fix: convert useComputedClass to defineClass
  packages/docs-next/.vitepress/theme/examples/button/base.vue
  packages/docs-next/package-lock.json
  packages/docs-next/package.json
  packages/oruga-next/src/components/autocomplete/Autocomplete.vue
  packages/oruga-next/src/components/button/Button.vue
  packages/oruga-next/src/components/carousel/Carousel.vue
  packages/oruga-next/src/components/carousel/CarouselItem.vue
  packages/oruga-next/src/components/checkbox/Checkbox.vue
  packages/oruga-next/src/components/collapse/Collapse.vue
  packages/oruga-next/src/components/datepicker/Datepicker.vue
  packages/oruga-next/src/components/datepicker/DatepickerMonth.vue
  packages/oruga-next/src/components/datepicker/DatepickerTable.vue
  packages/oruga-next/src/components/datepicker/DatepickerTableRow.vue
  packages/oruga-next/src/components/datepicker/PickerWrapper.vue
  packages/oruga-next/src/components/datetimepicker/Datetimepicker.vue
  packages/oruga-next/src/components/dropdown/Dropdown.vue
  packages/oruga-next/src/components/dropdown/DropdownItem.vue
  packages/oruga-next/src/components/field/Field.vue
  packages/oruga-next/src/components/field/FieldBody.vue
  packages/oruga-next/src/components/icon/Icon.vue
  packages/oruga-next/src/components/input/Input.vue
  packages/oruga-next/src/components/loading/Loading.vue
  packages/oruga-next/src/components/menu/Menu.vue
  packages/oruga-next/src/components/menu/MenuItem.vue
  packages/oruga-next/src/components/modal/Modal.vue
  packages/oruga-next/src/components/notification/Notification.vue
  packages/oruga-next/src/components/notification/NotificationNotice.vue
  packages/oruga-next/src/components/pagination/Pagination.vue
  packages/oruga-next/src/components/pagination/PaginationButton.vue
  packages/oruga-next/src/components/radio/Radio.vue
  packages/oruga-next/src/components/select/Select.vue
  packages/oruga-next/src/components/sidebar/Sidebar.vue
  packages/oruga-next/src/components/skeleton/Skeleton.vue
  packages/oruga-next/src/components/slider/Slider.vue
  packages/oruga-next/src/components/slider/SliderThumb.vue
  packages/oruga-next/src/components/slider/SliderTick.vue
  packages/oruga-next/src/components/steps/StepItem.vue
  packages/oruga-next/src/components/steps/Steps.vue
  packages/oruga-next/src/components/switch/Switch.vue
  packages/oruga-next/src/components/table/Table.vue
  packages/oruga-next/src/components/table/TableMobileSort.vue
  packages/oruga-next/src/components/tabs/TabItem.vue
  packages/oruga-next/src/components/tabs/Tabs.vue
  packages/oruga-next/src/components/tabs/types.ts
  packages/oruga-next/src/components/taginput/Taginput.vue
  packages/oruga-next/src/components/timepicker/Timepicker.vue
  packages/oruga-next/src/components/tooltip/Tooltip.vue
  packages/oruga-next/src/components/upload/Upload.vue
  packages/oruga-next/src/composables/defineClasses.ts
  packages/oruga-next/src/composables/index.ts
  packages/oruga-next/src/composables/useComputedClass.ts
  packages/oruga-next/src/types/utils.ts
Labels: bug, refactoring

#761 fix(autocomplete): close dropdown on enter or tab key press
  packages/docs-next/.vitepress/theme/examples/autocomplete/inspector.vue
  packages/docs-next/components/Dropdown.md
  packages/oruga-next/src/components/autocomplete/Autocomplete.vue
  packages/oruga-next/src/components/dropdown/Dropdown.vue
  packages/oruga-next/src/components/dropdown/types.ts
Labels: bug, enhancement, a11y

#762 feat: enhance a11y
  packages/docs-next/.vitepress/theme/examples/upload/base.vue
  packages/docs-next/components/Autocomplete.md
  packages/docs-next/components/Carousel.md
  packages/docs-next/components/Dropdown.md
  packages/docs-next/components/Input.md
  packages/docs-next/components/Modal.md
  packages/docs-next/components/Select.md
  packages/docs-next/components/Steps.md
  packages/docs-next/components/Upload.md
  packages/oruga-next/src/components/autocomplete/Autocomplete.vue
  packages/oruga-next/src/components/carousel/Carousel.vue
  packages/oruga-next/src/components/carousel/CarouselItem.vue
  packages/oruga-next/src/components/checkbox/Checkbox.vue
  packages/oruga-next/src/components/collapse/Collapse.vue
  packages/oruga-next/src/components/datepicker/DatepickerMonth.vue
  packages/oruga-next/src/components/datepicker/DatepickerTableRow.vue
  packages/oruga-next/src/components/datepicker/PickerWrapper.vue
  packages/oruga-next/src/components/dropdown/Dropdown.vue
  packages/oruga-next/src/components/dropdown/DropdownItem.vue
  packages/oruga-next/src/components/dropdown/types.ts
  packages/oruga-next/src/components/input/Input.vue
  packages/oruga-next/src/components/loading/Loading.vue
  packages/oruga-next/src/components/menu/MenuItem.vue
  packages/oruga-next/src/components/modal/Modal.vue
  packages/oruga-next/src/components/modal/types.ts
  packages/oruga-next/src/components/pagination/Pagination.vue
  packages/oruga-next/src/components/radio/Radio.vue
  packages/oruga-next/src/components/select/Select.vue
  packages/oruga-next/src/components/sidebar/Sidebar.vue
  packages/oruga-next/src/components/steps/StepItem.vue
  packages/oruga-next/src/components/steps/Steps.vue
  packages/oruga-next/src/components/switch/Switch.vue
  packages/oruga-next/src/components/tabs/TabItem.vue
  packages/oruga-next/src/components/tabs/Tabs.vue
  packages/oruga-next/src/components/taginput/Taginput.vue
  packages/oruga-next/src/components/upload/Upload.vue
Labels: a11y

#750 docs: update theme configs
  packages/docs-next/.vitepress/theme/index.ts
  packages/docs-next/.vitepress/theme/styles/theming.scss
  packages/docs-next/components/Dropdown.md
  packages/docs-next/package-lock.json
  packages/docs-next/package.json
Labels: documentation

#767 fix(taginput): forward expanded prop to Autocomplete component so that it's passed to dropdown
  packages/oruga-next/src/components/taginput/Taginput.vue
Labels: bug

#766 fix(notification): extend programmatic interface
  packages/docs-next/components/Notification.md
  packages/oruga-next/src/components/notification/NotificationNotice.vue
  packages/oruga-next/src/components/notification/NotificationProgrammatic.ts
Labels: enhancement

#773 build: update dependencies (Vue 3.4 | Vite 5.1)
  packages/oruga-next/package-lock.json
  packages/oruga-next/package.json
Labels: dependencies

#772 fix(taginput): fix rootClass inheritance
  packages/oruga-next/src/components/dropdown/Dropdown.vue
  packages/oruga-next/src/components/taginput/Taginput.vue
Labels: bug

#779 feat(pagination): add button tag property
  packages/docs-next/components/Pagination.md
  packages/oruga-next/src/components/pagination/Pagination.vue
  packages/oruga-next/src/components/pagination/PaginationButton.vue
  packages/oruga-next/src/components/types.ts
Labels: bug, enhancement

#782 fix(datepicker): refactor datepicker related components
  packages/oruga-next/src/components/datepicker/Datepicker.vue
  packages/oruga-next/src/components/datepicker/DatepickerMonth.vue
  packages/oruga-next/src/components/datepicker/DatepickerTable.vue
  packages/oruga-next/src/components/datepicker/DatepickerTableRow.vue
  packages/oruga-next/src/components/datepicker/index.ts
  packages/oruga-next/src/components/datepicker/types.ts
  packages/oruga-next/src/components/datepicker/useDatepickerMixins.ts
  packages/oruga-next/src/components/datepicker/utils.ts
  packages/oruga-next/src/components/datetimepicker/Datetimepicker.vue
  packages/oruga-next/src/components/timepicker/Timepicker.vue
  packages/oruga-next/src/components/timepicker/types.ts
  packages/oruga-next/src/components/timepicker/useTimepickerMixins.ts
Labels: bug, refactoring

#783 docs(script): update docs generation script
  packages/docs-next/components/Button.md
  packages/docs-next/components/Dropdown.md
  packages/docs-next/docgen.config.js
Labels: documentation

#787 fix(autocomplete): show empty slot available
  packages/oruga-next/src/components/autocomplete/Autocomplete.vue
Labels: bug

#785 fix(datetimepicker): fix vmodel reactivity
  packages/oruga-next/src/components/datetimepicker/Datetimepicker.vue
Labels: bug

#794 fix(composable): prevent scrolling parent error with parent null
  packages/oruga-next/src/composables/useScrollingParent.ts
Labels: bug

#793 feat(inputs): expose setFocus function for all input components
  packages/oruga-next/src/components/autocomplete/Autocomplete.vue
  packages/oruga-next/src/components/checkbox/Checkbox.vue
  packages/oruga-next/src/components/datepicker/Datepicker.vue
  packages/oruga-next/src/components/datetimepicker/Datetimepicker.vue
  packages/oruga-next/src/components/dropdown/Dropdown.vue
  packages/oruga-next/src/components/input/Input.vue
  packages/oruga-next/src/components/loading/Loading.vue
  packages/oruga-next/src/components/modal/Modal.vue
  packages/oruga-next/src/components/notification/NotificationNotice.vue
  packages/oruga-next/src/components/pagination/Pagination.vue
  packages/oruga-next/src/components/radio/Radio.vue
  packages/oruga-next/src/components/select/Select.vue
  packages/oruga-next/src/components/sidebar/Sidebar.vue
  packages/oruga-next/src/components/switch/Switch.vue
  packages/oruga-next/src/components/taginput/Taginput.vue
  packages/oruga-next/src/components/timepicker/Timepicker.vue
  packages/oruga-next/src/components/upload/Upload.vue
  packages/oruga-next/src/components/utils/PickerWrapper.vue
  packages/oruga-next/src/composables/useInputHandler.ts
Labels: enhancement

#789 fix(input): update password reveal
  packages/oruga-next/src/components/input/Input.vue
Labels: bug

#796 fix(autocomplete): unselected item autocomplete
  packages/oruga-next/src/components/autocomplete/Autocomplete.vue
Labels: bug

#798 fix(select): fix prop definition
  packages/oruga-next/src/components/select/Select.vue
Labels: bug

#797 feat(tabs|steps): add animation and animateInitially prop
  packages/docs-next/components/Steps.md
  packages/docs-next/components/Tabs.md
  packages/oruga-next/src/components/steps/StepItem.vue
  packages/oruga-next/src/components/steps/Steps.vue
  packages/oruga-next/src/components/steps/types.ts
  packages/oruga-next/src/components/tabs/TabItem.vue
  packages/oruga-next/src/components/tabs/Tabs.vue
  packages/oruga-next/src/components/tabs/types.ts
  packages/oruga-next/src/components/types.ts
Labels: enhancement

#803 docs: remove browser support section
  README.md
  packages/docs-next/documentation/index.md
Labels: documentation

#804 docs: remove oruga vue2 link
  packages/docs-next/.vitepress/config.ts
Labels: documentation

#808 docs: refactor files and components
  packages/docs/.vitepress/theme/components/ExampleViewer.vue
  packages/docs/.vitepress/theme/components/Expo.vue
  packages/docs/.vitepress/theme/components/Inspector.vue
  packages/docs/.vitepress/theme/components/InspectorWrapper.vue
  packages/docs/.vitepress/theme/components/ThemeSelector.vue
  packages/docs/.vitepress/theme/components/expo/VueTelescopeExpo.vue
  packages/docs/.vitepress/theme/index.ts
  packages/docs/.vitepress/theme/layout/Layout.vue
  packages/docs/.vitepress/themes.json
  packages/docs/tsconfig.json
Labels: refactoring

#810 fix: wrap focus listener into function
  packages/oruga/src/components/datepicker/Datepicker.vue
  packages/oruga/src/components/timepicker/Timepicker.vue
Labels: bug

#818 test: update test structure from cypress to vitest
  .github/workflows/build.yml
  package-lock.json
  package.json
  packages/oruga/cypress.config.ts
  packages/oruga/cypress/cypress.d.ts
  packages/oruga/cypress/plugins/index.js
  packages/oruga/cypress/support/commands.js
  packages/oruga/cypress/support/commands.ts
  packages/oruga/cypress/support/component-index.html
  packages/oruga/cypress/support/component.ts
  packages/oruga/cypress/support/index.js
  packages/oruga/package.json
  packages/oruga/src/components/autocomplete/tests/Autocomplete.spec.cy.ts
  packages/oruga/src/components/button/tests/Button.spec.cy.ts
  packages/oruga/src/components/checkbox/tests/Checkbox.spec.cy.ts
  packages/oruga/src/components/collapse/tests/Collapse.spec.cy.ts
  packages/oruga/src/components/menu/Menu.spec.cy.ts
  packages/oruga/src/components/menu/Menu.spec.js
  packages/oruga/src/components/menu/MenuItem.spec.cy.ts
  packages/oruga/src/components/menu/MenuItem.spec.js
  packages/oruga/src/components/menu/__snapshots__/Menu.spec.js.snap
  packages/oruga/src/components/menu/__snapshots__/MenuItem.spec.js.snap
  packages/oruga/src/components/menu/__snapshots__/MenuList.spec.js.snap
  packages/oruga/src/utils/InstanceRegistry.spec.js
  packages/oruga/src/utils/config.spec.cy.ts
  packages/oruga/tsconfig.json
  packages/oruga/vite.config.js
Labels: enhancement, refactoring
