Repository oruga-ui/oruga, pull requests merged in 2024-11, with the labels that each got.

#1091 fix(datepicker): add missing `effectScope` to defineClasses
  packages/oruga/src/components/datepicker/DatepickerTableRow.vue
Labels: bug

#1092 refactor(button): update props api
  packages/oruga/src/components/button/Button.vue
  packages/oruga/src/components/button/propts.ts
  packages/oruga/src/components/datepicker/examples/programmatically.vue
  packages/oruga/src/components/datepicker/examples/slots.vue
  packages/oruga/src/components/datepicker/examples/trigger.vue
  packages/oruga/src/components/datetimepicker/props.ts
  packages/oruga/src/components/dropdown/examples/programmatically.vue
Labels: refactoring

#1093 refactor: use useTemplateRef composable
  packages/oruga/src/components/autocomplete/Autocomplete.vue
  packages/oruga/src/components/carousel/Carousel.vue
  packages/oruga/src/components/checkbox/Checkbox.vue
  packages/oruga/src/components/datepicker/Datepicker.vue
  packages/oruga/src/components/datetimepicker/Datetimepicker.vue
  packages/oruga/src/components/dropdown/examples/inspector.vue
  packages/oruga/src/components/field/Field.vue
  packages/oruga/src/components/field/fieldInjection.ts
  packages/oruga/src/components/input/Input.vue
  packages/oruga/src/components/loading/Loading.vue
  packages/oruga/src/components/loading/examples/programmatically.vue
  packages/oruga/src/components/menu/Menu.vue
  packages/oruga/src/components/menu/MenuItem.vue
  packages/oruga/src/components/modal/Modal.vue
  packages/oruga/src/components/notification/NotificationNotice.vue
  packages/oruga/src/components/radio/Radio.vue
  packages/oruga/src/components/select/Select.vue
  packages/oruga/src/components/sidebar/Sidebar.vue
  packages/oruga/src/components/slider/Slider.vue
  packages/oruga/src/components/steps/Steps.vue
  packages/oruga/src/components/switch/Switch.vue
  packages/oruga/src/components/table/Table.vue
  packages/oruga/src/components/tabs/Tabs.vue
  packages/oruga/src/components/taginput/Taginput.vue
  packages/oruga/src/components/timepicker/Timepicker.vue
  packages/oruga/src/components/tooltip/Tooltip.vue
  packages/oruga/src/components/upload/Upload.vue
  packages/oruga/src/components/utils/PickerWrapper.vue
  packages/oruga/src/composables/useInputHandler.ts
  packages/oruga/src/composables/useParentProvider.ts
Labels: refactoring

#1094 feat(input): move the left icon element before the input element
  packages/oruga/src/components/autocomplete/tests/__snapshots__/autocomplete.test.ts.snap
  packages/oruga/src/components/datepicker/tests/__snapshots__/datepicker.test.ts.snap
  packages/oruga/src/components/datetimepicker/tests/__snapshots__/datetimepicker.test.ts.snap
  packages/oruga/src/components/input/Input.vue
  packages/oruga/src/components/input/tests/__snapshots__/input.test.ts.snap
  packages/oruga/src/components/taginput/tests/__snapshots__/taginput.test.ts.snap
  packages/oruga/src/components/timepicker/tests/__snapshots__/timepicker.test.ts.snap
Labels: enhancement, breaking

#1095 chore: update dependencies
  package-lock.json
  package.json
  packages/docs/package.json
  packages/examples/package.json
  packages/oruga/package.json
Labels: dependencies

#1096 build: fix types generation
  packages/oruga/vite.config.ts
Labels: bug

#1097 feat(menu): refactor class names to match other components class name patterns
  packages/oruga/src/components/menu/MenuItem.vue
  packages/oruga/src/components/menu/examples/inspector.vue
  packages/oruga/src/components/menu/tests/__snapshots__/menu.integration.test.ts.snap
  packages/oruga/src/components/menu/tests/menu.integration.test.ts
Labels: breaking, refactoring

#1098 refactor(table): update types
  packages/docs/components/Table.md
  packages/oruga/src/components/table/Table.vue
  packages/oruga/src/components/table/TableColumn.vue
  packages/oruga/src/components/table/examples/checkable.vue
  packages/oruga/src/components/table/examples/detailed.vue
  packages/oruga/src/components/table/examples/pagination.vue
  packages/oruga/src/components/table/props.ts
  packages/oruga/src/components/table/types.ts
  packages/oruga/src/composables/useObjectMap.ts
Labels: refactoring

#1100 fix: solve issues
  package.json
  packages/docs/.vitepress/theme/components/ExampleViewer.vue
  packages/oruga/src/components/autocomplete/Autocomplete.vue
  packages/oruga/src/components/autocomplete/examples/infinite-scroll.vue
  packages/oruga/src/components/autocomplete/examples/objects-array.vue
  packages/oruga/src/components/button/examples/index.vue
  packages/oruga/src/components/button/examples/sizes.vue
  packages/oruga/src/components/button/examples/tags.vue
  packages/oruga/src/components/checkbox/Checkbox.vue
  packages/oruga/src/components/checkbox/props.ts
  packages/oruga/src/components/datetimepicker/tests/__snapshots__/datetimepicker.test.ts.snap
  packages/oruga/src/components/dropdown/Dropdown.vue
  packages/oruga/src/components/notification/examples/_notification-form.vue
  packages/oruga/src/components/notification/examples/programmatic.vue
  packages/oruga/src/components/notification/examples/programmatically.vue
  packages/oruga/src/components/radio/props.ts
  packages/oruga/src/components/sidebar/Sidebar.vue
  packages/oruga/src/components/sidebar/examples/inline.vue
  packages/oruga/src/components/sidebar/props.ts
  packages/oruga/src/components/slider/Slider.vue
  packages/oruga/src/components/steps/StepItem.vue
  packages/oruga/src/components/steps/Steps.vue
  packages/oruga/src/components/steps/examples/base.vue
  packages/oruga/src/components/steps/props.ts
  packages/oruga/src/components/steps/tests/__snapshots__/steps.integration.test.ts.snap
  packages/oruga/src/components/steps/tests/steps.axe.test.ts
  packages/oruga/src/components/steps/tests/steps.test.ts
  packages/oruga/src/components/steps/types.ts
  packages/oruga/src/components/switch/Switch.vue
  packages/oruga/src/components/switch/props.ts
  packages/oruga/src/components/table/Table.vue
  packages/oruga/src/components/table/examples/detailed.vue
  packages/oruga/src/components/table/props.ts
  packages/oruga/src/components/tabs/TabItem.vue
  packages/oruga/src/components/tabs/Tabs.vue
  packages/oruga/src/components/tabs/examples/base.vue
  packages/oruga/src/components/tabs/examples/sizes.vue
  packages/oruga/src/components/tabs/tests/__snapshots__/tabs.integration.test.ts.snap
  packages/oruga/src/components/tabs/tests/tabs.axe.test.ts
  packages/oruga/src/components/tabs/types.ts
  packages/oruga/src/components/types.ts
Labels: bug

#1104 docs: update theme dependencies
  package-lock.json
  packages/docs/.vitepress/theme/index.ts
  packages/docs/.vitepress/theme/styles/theming.scss
  packages/docs/.vitepress/theme/styles/vitepress.scss
  packages/docs/.vitepress/themes.json
  packages/docs/components/Button.md
  packages/docs/components/Datepicker.md
  packages/docs/components/Menu.md
  packages/docs/components/Steps.md
  packages/docs/package.json
  packages/docs/themes/theme-oruga.md
Labels: documentation

#1107 fix(table): remove generic type strictness
  packages/oruga/src/components/table/Table.vue
  packages/oruga/src/components/table/TableColumn.vue
  packages/oruga/src/components/table/examples/base.vue
  packages/oruga/src/components/table/examples/checkable.vue
  packages/oruga/src/components/table/examples/searchable.vue
  packages/oruga/src/components/table/examples/selection.vue
  packages/oruga/src/components/table/examples/sticky.vue
  packages/oruga/src/components/table/index.ts
  packages/oruga/src/components/table/props.ts
  packages/oruga/src/components/table/types.ts
Labels: bug

#1112 docs: add `theme-light` specification
  packages/docs/.vitepress/theme/components/ThemeSelector.vue
  packages/docs/.vitepress/theme/layout/Layout.vue
Labels: documentation

#1114 fix(programmatic): solve wrong `events` prop type
  packages/oruga/src/components/modal/props.ts
  packages/oruga/src/components/notification/props.ts
  packages/oruga/src/components/sidebar/props.ts
  packages/oruga/src/components/steps/props.ts
  packages/oruga/src/components/tabs/props.ts
  packages/oruga/src/types/utils.ts
Labels: bug

#1109 fix(dropdown): solve closing issue when has `multiple` property
  packages/oruga/src/components/dropdown/Dropdown.vue
  packages/oruga/src/components/dropdown/tests/DropdownExample.vue
  packages/oruga/src/components/dropdown/tests/__snapshots__/dropdown.integration.test.ts.snap
  packages/oruga/src/components/dropdown/tests/__snapshots__/dropdown.test.ts.snap
  packages/oruga/src/components/dropdown/tests/dropdown.integration.test.ts
  packages/oruga/src/components/dropdown/tests/dropdown.test.ts
Labels: bug

#1110 fix(programmatic): readd `OrugaProgrammatic` interface to the export
  packages/oruga/src/components/loading/examples/programmatically.vue
  packages/oruga/src/components/loading/useLoadingProgrammatic.ts
  packages/oruga/src/components/modal/useModalProgrammatic.ts
  packages/oruga/src/components/notification/useNotificationProgrammatic.ts
  packages/oruga/src/components/programmatic/useProgrammatic.ts
  packages/oruga/src/components/sidebar/examples/programmatically.vue
  packages/oruga/src/components/sidebar/useSidebarProgrammatic.ts
  packages/oruga/src/index.ts
Labels: bug

#1113 refactor: change defineEmits to type-declaration approach
  .gitignore
  packages/oruga/src/components/autocomplete/Autocomplete.vue
  packages/oruga/src/components/carousel/Carousel.vue
  packages/oruga/src/components/checkbox/Checkbox.vue
  packages/oruga/src/components/collapse/Collapse.vue
  packages/oruga/src/components/datepicker/Datepicker.vue
  packages/oruga/src/components/datepicker/DatepickerMonth.vue
  packages/oruga/src/components/datepicker/DatepickerTable.vue
  packages/oruga/src/components/datepicker/DatepickerTableRow.vue
  packages/oruga/src/components/datetimepicker/Datetimepicker.vue
  packages/oruga/src/components/dropdown/Dropdown.vue
  packages/oruga/src/components/dropdown/DropdownItem.vue
  packages/oruga/src/components/dropdown/tests/__snapshots__/dropdown.test.ts.snap
  packages/oruga/src/components/dropdown/tests/dropdown.test.ts
  packages/oruga/src/components/input/Input.vue
  packages/oruga/src/components/input/tests/input.test.ts
  packages/oruga/src/components/loading/Loading.vue
  packages/oruga/src/components/menu/MenuItem.vue
  packages/oruga/src/components/modal/Modal.vue
  packages/oruga/src/components/notification/Notification.vue
  packages/oruga/src/components/notification/NotificationNotice.vue
  packages/oruga/src/components/pagination/Pagination.vue
  packages/oruga/src/components/pagination/PaginationButton.vue
  packages/oruga/src/components/radio/Radio.vue
  packages/oruga/src/components/radio/tests/radio.test.ts
  packages/oruga/src/components/select/Select.vue
  packages/oruga/src/components/sidebar/Sidebar.vue
  packages/oruga/src/components/slider/Slider.vue
  packages/oruga/src/components/slider/SliderThumb.vue
  packages/oruga/src/components/steps/StepItem.vue
  packages/oruga/src/components/steps/Steps.vue
  packages/oruga/src/components/switch/Switch.vue
  packages/oruga/src/components/switch/tests/switch.test.ts
  packages/oruga/src/components/table/TableMobileSort.vue
  packages/oruga/src/components/table/TablePagination.vue
  packages/oruga/src/components/tabs/TabItem.vue
  packages/oruga/src/components/tabs/Tabs.vue
  packages/oruga/src/components/taginput/Taginput.vue
  packages/oruga/src/components/timepicker/Timepicker.vue
  packages/oruga/src/components/tooltip/Tooltip.vue
  packages/oruga/src/components/upload/Upload.vue
  packages/oruga/src/components/utils/PickerWrapper.vue
  packages/oruga/src/components/utils/PositionWrapper.vue
Labels: refactoring

#1117 fix(programmatic): fix typo in NotificationProgrammaticOptions type
  packages/oruga/src/components/notification/useNotificationProgrammatic.ts
Labels: bug

#1118 fix(programmatic): make options interface extandable
  packages/oruga/src/components/programmatic/useProgrammatic.ts
  packages/oruga/src/types/utils.ts
Labels: bug

#1123 refactor: update props to type-based declaration approach
  packages/oruga/src/components/carousel/Carousel.vue
  packages/oruga/src/components/carousel/CarouselItem.vue
  packages/oruga/src/components/carousel/props.ts
  packages/oruga/src/components/collapse/Collapse.vue
  packages/oruga/src/components/collapse/props.ts
  packages/oruga/src/components/field/Field.vue
  packages/oruga/src/components/field/fieldInjection.ts
  packages/oruga/src/components/field/props.ts
  packages/oruga/src/components/menu/Menu.vue
  packages/oruga/src/components/menu/MenuItem.vue
  packages/oruga/src/components/menu/props.ts
  packages/oruga/src/components/modal/Modal.vue
  packages/oruga/src/components/modal/tests/__snapshots__/modal.test.ts.snap
  packages/oruga/src/components/pagination/Pagination.vue
  packages/oruga/src/components/pagination/examples/base.vue
  packages/oruga/src/components/pagination/props.ts
  packages/oruga/src/components/skeleton/Skeleton.vue
  packages/oruga/src/components/skeleton/props.ts
  packages/oruga/src/components/tooltip/Tooltip.vue
  packages/oruga/src/components/tooltip/props.ts
Labels: refactoring

#1122 build: update node to v22
  .github/CONTRIBUTING.md
  .github/workflows/build.yml
  .github/workflows/commit-lint.yml
  .github/workflows/publish-pre-release.yml
  .github/workflows/publish-release.yml
  .github/workflows/test.yml
  .github/workflows/ts-check.yml
  package-lock.json
  packages/docs/package.json
  packages/examples/package.json
  packages/oruga/package.json
  packages/oruga/tsconfig.node.json
Labels: dependencies

#1124 docs(docgen): improve documentation code generation
  package-lock.json
  packages/docs/.vitepress/config.ts
  packages/docs/.vitepress/theme/components/ThemeSelector.vue
  packages/docs/.vitepress/theme/index.ts
  packages/docs/components/Autocomplete.md
  packages/docs/components/Button.md
  packages/docs/components/Carousel.md
  packages/docs/components/Checkbox.md
  packages/docs/components/Collapse.md
  packages/docs/components/Datepicker.md
  packages/docs/components/Datetimepicker.md
  packages/docs/components/Dropdown.md
  packages/docs/components/Field.md
  packages/docs/components/Icon.md
  packages/docs/components/Input.md
  packages/docs/components/Loading.md
  packages/docs/components/Menu.md
  packages/docs/components/Modal.md
  packages/docs/components/Notification.md
  packages/docs/components/Pagination.md
  packages/docs/components/Radio.md
  packages/docs/components/Select.md
  packages/docs/components/Sidebar.md
  packages/docs/components/Skeleton.md
  packages/docs/components/Slider.md
  packages/docs/components/Steps.md
  packages/docs/components/Switch.md
  packages/docs/components/Table.md
  packages/docs/components/Tabs.md
  packages/docs/components/Taginput.md
  packages/docs/components/Timepicker.md
  packages/docs/components/Tooltip.md
  packages/docs/components/Upload.md
  packages/docs/docgen.config.js
  packages/docs/package.json
  packages/docs/src/docgen.ts
  packages/docs/src/parser/parser.ts
  packages/docs/src/parser/vue-component-meta-helper.ts
  packages/docs/src/parser/vue-docgen-api-helper.ts
  packages/docs/src/templates/classes.ts
  packages/docs/src/templates/component.ts
  packages/docs/src/templates/events.ts
  packages/docs/src/templates/examples.ts
  packages/docs/src/templates/props.ts
  packages/docs/src/templates/slots.ts
  packages/docs/src/templates/style.ts
  packages/docs/src/themes-helper.ts
  packages/docs/src/themes.json
  packages/docs/src/utils.ts
  packages/docs/tsconfig.json
  packages/oruga/src/components/autocomplete/Autocomplete.vue
  packages/oruga/src/components/autocomplete/examples/infinite-scroll.vue
  packages/oruga/src/components/carousel/props.ts
  packages/oruga/src/components/taginput/Taginput.vue
  packages/oruga/src/composables/useInputHandler.ts
Labels: documentation

#1129 feat(field): add unique label Id to field injection
  packages/oruga/src/components/field/Field.vue
  packages/oruga/src/components/field/fieldInjection.ts
Labels: a11y

#1130 feat(checkbox): support w3c WAI-ARIA pattern
  packages/docs/components/Checkbox.md
  packages/oruga/src/components/checkbox/Checkbox.vue
  packages/oruga/src/components/checkbox/tests/__snapshots__/checkbox.test.ts.snap
  packages/oruga/src/components/checkbox/tests/checkbox.axe.test.ts
  packages/oruga/src/components/checkbox/tests/checkbox.test.ts
Labels: a11y

#1131 feat(switch): support w3c WAI-ARIA pattern
  packages/docs/components/Switch.md
  packages/oruga/src/components/switch/Switch.vue
  packages/oruga/src/components/switch/tests/__snapshots__/switch.test.ts.snap
  packages/oruga/src/components/switch/tests/switch.axe.test.ts
  packages/oruga/src/components/switch/tests/switch.test.ts
  packages/oruga/src/composables/useInputHandler.ts
Labels: a11y

#1132 feat(radio): support w3c WAI-ARIA pattern
  packages/oruga/src/components/radio/Radio.vue
  packages/oruga/src/components/radio/examples/base.vue
  packages/oruga/src/components/radio/examples/sizes.vue
  packages/oruga/src/components/radio/examples/variants.vue
  packages/oruga/src/components/radio/tests/__snapshots__/radio.test.ts.snap
  packages/oruga/src/components/radio/tests/radio.axe.test.ts
  packages/oruga/src/components/radio/tests/radio.test.ts
Labels: a11y

#1137 fix: change `crypto.randomUUID()` with a sequential id generation
  packages/oruga/src/components/autocomplete/Autocomplete.vue
  packages/oruga/src/components/dropdown/Dropdown.vue
  packages/oruga/src/components/select/Select.vue
  packages/oruga/src/components/steps/Steps.vue
  packages/oruga/src/components/switch/tests/switch.axe.test.ts
  packages/oruga/src/components/table/Table.vue
  packages/oruga/src/components/tabs/Tabs.vue
  packages/oruga/src/components/taginput/Taginput.vue
  packages/oruga/src/composables/index.ts
  packages/oruga/src/composables/tests/useOptions.test.ts
  packages/oruga/src/composables/useObjectMap.ts
  packages/oruga/src/composables/useOptions.ts
  packages/oruga/src/composables/useParentProvider.ts
  packages/oruga/src/composables/useSequentialId.ts
Labels: bug, refactoring

#1119 fix(tabs): set fixed `tab` and `tabpanel` values for native `role` attribute
  packages/docs/components/Tabs.md
  packages/oruga/src/components/tabs/TabItem.vue
  packages/oruga/src/components/tabs/Tabs.vue
  packages/oruga/src/components/tabs/props.ts
  packages/oruga/src/components/tabs/tests/__snapshots__/tabs.integration.test.ts.snap
Labels: enhancement, a11y

#1121 feat(tabs): update keyboard navigation to match W3C WAI standart
  packages/docs/components/Tabs.md
  packages/oruga/src/components/tabs/Tabs.vue
  packages/oruga/src/components/tabs/props.ts
Labels: enhancement, a11y
