Repository oruga-ui/oruga, pull requests merged in 2024-03, with the labels that each got.

#830 fix(modal): make property `width` reactive
  packages/oruga/src/components/modal/Modal.vue
Labels: bug

#831 fix(programmatic): fix ProgrammaticExpose type
  packages/oruga/src/types/programmatic.ts
Labels: bug

#836 fix(table): fix table-column searchable slot property bug
  packages/docs/components/Table.md
  packages/oruga/src/components/table/TableColumn.vue
Labels: bug

#822 docs: update button example
  packages/docs/.vitepress/theme/examples/button/base.vue
Labels: documentation

#834 fix(helper): remove unintended unref function
  packages/oruga/src/composables/defineClasses.ts
  packages/oruga/src/utils/helpers.ts
Labels: bug

#824 fix(ConfigPlugin): export ConfigPlugin
  packages/oruga/src/index.ts
Labels: bug

#832 fix(table): `stickyHeaderClass` should not display by default
  packages/oruga/src/components/table/Table.vue
Labels: bug

#840 fix(table): set TableColumn `customSort` type to `unknown`
  packages/oruga/src/components/table/TableColumn.vue
Labels: bug

#843 fix(upload): fix upload input bindung
  packages/oruga/src/components/upload/Upload.vue
Labels: bug

#842 fix(table): fix `page-change` event sending old value
  packages/docs/components/Table.md
  packages/oruga/src/components/table/TablePagination.vue
Labels: bug

#844 fix(build): add volar types export
  packages/oruga/package.json
Labels: bug

#845 feat(table): make `bordered`, `striped`, `narrowed` and `hoverable` configurable
  packages/oruga/src/components/table/Table.vue
  packages/oruga/src/components/types.ts
Labels: enhancement

#841 test(dropdown): add dropdown tests
  packages/oruga/src/components/dropdown/Dropdown.vue
  packages/oruga/src/components/dropdown/DropdownItem.vue
  packages/oruga/src/components/dropdown/tests/DropdownExample.vue
  packages/oruga/src/components/dropdown/tests/__snapshots__/dropdown.test.ts.snap
  packages/oruga/src/components/dropdown/tests/dropdown.integration.test.ts
  packages/oruga/src/components/dropdown/tests/dropdown.test.ts
  packages/oruga/src/components/dropdown/tests/dropdownitem.test.ts
Labels: enhancement

#847 docs: update props
  packages/docs/components/Dropdown.md
  packages/docs/components/Table.md
Labels: documentation

#848 fix(table): prevent TableColumn function props trigger recursive reactivity
  packages/docs/components/Table.md
  packages/oruga/src/components/table/Table.vue
  packages/oruga/src/components/table/TableColumn.vue
  packages/oruga/src/components/table/types.ts
Labels: bug

#850 refactor(helpers): cleanup helpers
  packages/oruga/src/utils/helpers.ts
Labels: refactoring

#851 refactor: enhance `useParentProvider` composable type support
  packages/oruga/src/components/carousel/Carousel.vue
  packages/oruga/src/components/carousel/CarouselItem.vue
  packages/oruga/src/components/carousel/types.ts
  packages/oruga/src/components/dropdown/DropdownItem.vue
  packages/oruga/src/components/menu/Menu.vue
  packages/oruga/src/components/menu/MenuItem.vue
  packages/oruga/src/components/menu/types.ts
  packages/oruga/src/components/slider/SliderTick.vue
  packages/oruga/src/components/steps/StepItem.vue
  packages/oruga/src/components/table/Table.vue
  packages/oruga/src/components/tabs/TabItem.vue
  packages/oruga/src/composables/useParentProvider.ts
Labels: refactoring

#855 refactor: rename programmatic props type
  packages/oruga/src/components/loading/LoadingProgrammatic.ts
  packages/oruga/src/components/modal/ModalProgrammatic.ts
  packages/oruga/src/components/notification/NotificationProgrammatic.ts
  packages/oruga/src/components/sidebar/SidebarProgrammatic.ts
Labels: refactoring

#857 docs: update programmatic config usage description
  packages/docs/documentation/customisation.md
  packages/docs/documentation/index.md
  packages/docs/documentation/themes.md
  packages/oruga/src/types/config.ts
Labels: documentation

#846 tests(steps): add axe tests, correct steps aria
  package-lock.json
  packages/oruga/package.json
  packages/oruga/src/__tests__/vitest.setup.ts
  packages/oruga/src/components/steps/Steps.vue
  packages/oruga/src/components/steps/tests/StepsExample.vue
  packages/oruga/src/components/steps/tests/steps.axe.test.ts
  packages/oruga/vite.config.js
Labels: enhancement, a11y

#867 fix: fix type generation script
  .scripts/gen-comp-types.mjs
Labels: bug

#868 test: update test environment
  package-lock.json
  packages/oruga/package.json
  packages/oruga/src/__tests__/vitest.setup.ts
  packages/oruga/src/components/dropdown/tests/__snapshots__/dropdown.test.ts.snap
  packages/oruga/src/components/dropdown/tests/dropdown.integration.test.ts
  packages/oruga/src/components/dropdown/tests/dropdown.test.ts
  packages/oruga/src/components/dropdown/tests/dropdownitem.test.ts
  packages/oruga/src/components/steps/tests/StepsExample.vue
  packages/oruga/tsconfig.json
  packages/oruga/vite.config.js
Labels: refactoring

#859 fix(autocomplete): adjust active state behavior
  packages/docs/.vitepress/theme/examples/autocomplete/objects-array.vue
  packages/oruga/src/components/autocomplete/Autocomplete.vue
Labels: bug

#869 fix: resolve maximum recursive update exceeded in tests
  packages/oruga/src/components/autocomplete/Autocomplete.vue
  packages/oruga/src/components/dropdown/Dropdown.vue
  packages/oruga/src/components/tooltip/Tooltip.vue
  packages/oruga/src/components/utils/PositionWrapper.vue
  packages/oruga/src/composables/useEventListener.ts
  packages/oruga/src/composables/useParentProvider.ts
Labels: bug

#870 fix(tabs): fix disable animation
  packages/oruga/src/components/steps/StepItem.vue
  packages/oruga/src/components/tabs/TabItem.vue
Labels: bug

#871 fix(tabs): move inherit attrs to div instead of transition
  packages/oruga/src/components/steps/StepItem.vue
  packages/oruga/src/components/tabs/TabItem.vue
Labels: enhancement

#874 docs: add ConfigPlugin deprecated docs
  packages/oruga/src/index.ts
Labels: documentation
