Repository oruga-ui/oruga, pull requests merged in 2025-05, with the labels that each got.

#1293 docs: update section links
  packages/docs/documentation/customisation.md
  packages/docs/documentation/themes.md
Labels: documentation

#861 feat(breadcrumb): add breadcrumb component
  packages/docs/components/Breadcrumb.md
  packages/docs/components/Dropdown.md
  packages/docs/src/docgen.ts
  packages/oruga/components.d.ts
  packages/oruga/src/components/breadcrumb/Breadcrumb.vue
  packages/oruga/src/components/breadcrumb/BreadcrumbItem.vue
  packages/oruga/src/components/breadcrumb/examples/base.vue
  packages/oruga/src/components/breadcrumb/examples/icons.vue
  packages/oruga/src/components/breadcrumb/examples/index.vue
  packages/oruga/src/components/breadcrumb/examples/inspector.vue
  packages/oruga/src/components/breadcrumb/examples/options.vue
  packages/oruga/src/components/breadcrumb/examples/positions.vue
  packages/oruga/src/components/breadcrumb/examples/readme.md
  packages/oruga/src/components/breadcrumb/examples/separators.vue
  packages/oruga/src/components/breadcrumb/examples/sizes.vue
  packages/oruga/src/components/breadcrumb/examples/tags.vue
  packages/oruga/src/components/breadcrumb/examples/variants.vue
  packages/oruga/src/components/breadcrumb/index.ts
  packages/oruga/src/components/breadcrumb/props.ts
  packages/oruga/src/components/breadcrumb/tests/__snapshots__/breadcrumb.test.ts.snap
  packages/oruga/src/components/breadcrumb/tests/breadcrumb.test.ts
  packages/oruga/src/components/breadcrumb/tests/breadcrumbitem.test.ts
  packages/oruga/src/components/breadcrumb/types.ts
  packages/oruga/src/components/button/examples/index.vue
  packages/oruga/src/components/dropdown/props.ts
  packages/oruga/src/components/dropdown/tests/dropdown.test.ts
  packages/oruga/src/components/icon/props.ts
  packages/oruga/src/components/index.ts
  packages/oruga/src/components/menu/MenuItem.vue
  packages/oruga/src/components/menu/examples/index.vue
  packages/oruga/src/components/plugins.ts
  packages/oruga/src/components/types.ts
  packages/oruga/src/composables/useOptions.ts
  packages/oruga/src/types/config.ts
  packages/oruga/volar.d.ts
Labels: feature

#1292 feat(field): allow multiple field messages
  packages/docs/components/Field.md
  packages/oruga/src/components/field/Field.vue
  packages/oruga/src/components/field/examples/base.vue
  packages/oruga/src/components/field/fieldInjection.ts
  packages/oruga/src/components/field/props.ts
  packages/oruga/src/components/field/tests/field.test.ts
Labels: enhancement

#1296 feat(notification): add `rounded` prop and class
  packages/docs/components/Notification.md
  packages/oruga/src/components/notification/Notification.vue
  packages/oruga/src/components/notification/examples/inspector.vue
  packages/oruga/src/components/notification/props.ts
  packages/oruga/src/components/types.ts
Labels: enhancement

#1302 chore: update dependencies
  package-lock.json
  package.json
  packages/docs/components/Button.md
  packages/docs/package.json
  packages/examples/package.json
  packages/oruga/package.json
Labels: dependencies

#1303 docs: fix typos
  packages/docs/components/Dropdown.md
  packages/docs/components/Pagination.md
  packages/docs/components/Sidebar.md
  packages/docs/components/Upload.md
  packages/oruga/src/components/autocomplete/tests/__snapshots__/autocomplete.test.ts.snap
  packages/oruga/src/components/datepicker/tests/__snapshots__/datepicker.test.ts.snap
  packages/oruga/src/components/datetimepicker/tests/__snapshots__/datetimepicker.test.ts.snap
  packages/oruga/src/components/dropdown/Dropdown.vue
  packages/oruga/src/components/dropdown/tests/__snapshots__/dropdown.test.ts.snap
  packages/oruga/src/components/pagination/Pagination.vue
  packages/oruga/src/components/pagination/tests/__snapshots__/pagination.test.ts.snap
  packages/oruga/src/components/sidebar/Sidebar.vue
  packages/oruga/src/components/sidebar/tests/__snapshots__/sidebar.test.ts.snap
  packages/oruga/src/components/taginput/Taginput.vue
  packages/oruga/src/components/taginput/examples/index.vue
  packages/oruga/src/components/taginput/tests/__snapshots__/taginput.test.ts.snap
  packages/oruga/src/components/timepicker/tests/__snapshots__/timepicker.test.ts.snap
  packages/oruga/src/components/upload/Upload.vue
  packages/oruga/src/components/upload/tests/__snapshots__/upload.test.ts.snap
Labels: documentation

#1297 docs(notification): enhance programmatic examples
  packages/oruga/src/components/loading/examples/index.vue
  packages/oruga/src/components/modal/examples/index.vue
  packages/oruga/src/components/notification/examples/index.vue
  packages/oruga/src/components/notification/examples/programmatically-custom.vue
  packages/oruga/src/components/notification/examples/programmatically-default.vue
  packages/oruga/src/components/notification/examples/programmatically-toast.vue
  packages/oruga/src/components/sidebar/examples/index.vue
Labels: documentation

#1306 fix(programmatic): resolve inconsistent `close` event args
  packages/oruga/src/components/loading/Loading.vue
  packages/oruga/src/components/loading/tests/useLoadingProgrammatic.test.ts
  packages/oruga/src/components/modal/Modal.vue
  packages/oruga/src/components/modal/tests/useModalProgrammatic.test.ts
  packages/oruga/src/components/notification/NotificationNotice.vue
  packages/oruga/src/components/notification/tests/useNotificationProgrammatic.test.ts
  packages/oruga/src/components/programmatic/tests/useProgrammatic.test.ts
  packages/oruga/src/components/sidebar/Sidebar.vue
  packages/oruga/src/components/sidebar/tests/useSidebarProgrammatic.test.ts
Labels: bug

#1301 feat(tag): add Tag component
  packages/docs/components/Tag.md
  packages/oruga/components.d.ts
  packages/oruga/src/components/index.ts
  packages/oruga/src/components/plugins.ts
  packages/oruga/src/components/tag/Tag.vue
  packages/oruga/src/components/tag/examples/badge.vue
  packages/oruga/src/components/tag/examples/base.vue
  packages/oruga/src/components/tag/examples/closable.vue
  packages/oruga/src/components/tag/examples/index.vue
  packages/oruga/src/components/tag/examples/inspector.vue
  packages/oruga/src/components/tag/examples/readme.md
  packages/oruga/src/components/tag/examples/sizes.vue
  packages/oruga/src/components/tag/examples/variants.vue
  packages/oruga/src/components/tag/index.ts
  packages/oruga/src/components/tag/props.ts
  packages/oruga/src/components/tag/tests/__snapshots__/tag.test.ts.snap
  packages/oruga/src/components/tag/tests/tag.test.ts
  packages/oruga/src/components/types.ts
  packages/oruga/volar.d.ts
Labels: feature

#1304 docs: update general documentation
  README.md
  packages/docs/.vitepress/config.ts
  packages/docs/documentation/composables.md
  packages/docs/documentation/configuration.md
  packages/docs/documentation/index.md
  packages/docs/documentation/themes.md
  packages/docs/index.md
Labels: documentation

#1308 docs(collapse): update documentation
  packages/docs/components/Collapse.md
  packages/oruga/src/components/collapse/Collapse.vue
  packages/oruga/src/components/collapse/examples/accordion.vue
  packages/oruga/src/components/collapse/examples/base.vue
  packages/oruga/src/components/collapse/examples/readme.md
Labels: documentation

#1310 feat(modal): add alert dialog pattern support
  packages/docs/.vitepress/theme/styles/theming.scss
  packages/docs/components/Modal.md
  packages/oruga/src/components/modal/Modal.vue
  packages/oruga/src/components/modal/examples/alert.vue
  packages/oruga/src/components/modal/examples/base.vue
  packages/oruga/src/components/modal/examples/component.vue
  packages/oruga/src/components/modal/examples/index.vue
  packages/oruga/src/components/modal/examples/readme.md
  packages/oruga/src/components/modal/examples/teleport.vue
  packages/oruga/src/components/modal/props.ts
  packages/oruga/src/components/types.ts
  packages/oruga/src/composables/useTrapFocus.ts
Labels: enhancement, a11y

#1314 refactor(icon): replace internal `both` prop with global config
  packages/docs/.vitepress/theme/index.ts
  packages/oruga/src/components/button/Button.vue
  packages/oruga/src/components/button/props.ts
  packages/oruga/src/components/carousel/Carousel.vue
  packages/oruga/src/components/icon/Icon.vue
  packages/oruga/src/components/icon/examples/base.vue
  packages/oruga/src/components/icon/props.ts
  packages/oruga/src/components/icon/tests/__snapshots__/icon.test.ts.snap
  packages/oruga/src/components/input/Input.vue
  packages/oruga/src/components/loading/Loading.vue
  packages/oruga/src/components/modal/Modal.vue
  packages/oruga/src/components/notification/Notification.vue
  packages/oruga/src/components/pagination/Pagination.vue
  packages/oruga/src/components/select/Select.vue
  packages/oruga/src/components/steps/Steps.vue
  packages/oruga/src/components/table/Table.vue
  packages/oruga/src/components/table/TableMobileSort.vue
  packages/oruga/src/components/tag/Tag.vue
  packages/oruga/src/components/tag/tests/__snapshots__/tag.test.ts.snap
  packages/oruga/src/components/taginput/Taginput.vue
  packages/oruga/src/types/config.ts
  packages/oruga/src/utils/icons.ts
Labels: refactoring

#1309 fix(icon): add icon to tab order when `clickable`
  packages/docs/components/Icon.md
  packages/docs/components/Modal.md
  packages/oruga/src/components/carousel/Carousel.vue
  packages/oruga/src/components/carousel/tests/__snapshots__/carousel.test.ts.snap
  packages/oruga/src/components/icon/Icon.vue
  packages/oruga/src/components/icon/props.ts
  packages/oruga/src/components/input/Input.vue
  packages/oruga/src/components/modal/Modal.vue
  packages/oruga/src/components/modal/props.ts
  packages/oruga/src/components/modal/tests/__snapshots__/modal.test.ts.snap
  packages/oruga/src/components/notification/Notification.vue
  packages/oruga/src/components/select/Select.vue
  packages/oruga/src/components/table/Table.vue
  packages/oruga/src/components/tag/Tag.vue
  packages/oruga/src/components/taginput/Taginput.vue
  packages/oruga/src/components/types.ts
Labels: bug

#1318 feat(input): expose `checkHtml5Validity` method
  packages/oruga/src/components/autocomplete/Autocomplete.vue
  packages/oruga/src/components/checkbox/Checkbox.vue
  packages/oruga/src/components/datetimepicker/Datetimepicker.vue
  packages/oruga/src/components/input/Input.vue
  packages/oruga/src/components/radio/Radio.vue
  packages/oruga/src/components/select/Select.vue
  packages/oruga/src/components/switch/Switch.vue
  packages/oruga/src/components/taginput/Taginput.vue
  packages/oruga/src/components/upload/Upload.vue
  packages/oruga/src/components/utils/PickerWrapper.vue
  packages/oruga/src/composables/tests/useInputHandler.browser.test.ts
Labels: enhancement
