Repository oruga-ui/oruga, pull requests merged in 2025-02, with the labels that each got.

#1173 fix(tabs|steps): replace falsly check with nullish check for default `value` prop
  packages/oruga/src/components/steps/StepItem.vue
  packages/oruga/src/components/tabs/TabItem.vue
  packages/oruga/src/components/tabs/tests/tabs.test.ts
Labels: bug

#1176 feat(table): rename prop `debounceSearch` to `filterDebounce` to match other props
  packages/docs/components/Table.md
  packages/oruga/src/components/table/Table.vue
  packages/oruga/src/components/table/props.ts
  packages/oruga/src/components/table/tests/table.test.ts
  packages/oruga/src/components/types.ts
Labels: enhancement, breaking

#1177 fix(taginput): prevent item removing when is `disabled`
  packages/oruga/src/components/taginput/Taginput.vue
Labels: bug

#1175 feat(programmatic): make programmatic components devtools compatible
  packages/docs/components/Notification.md
  packages/docs/documentation/composables.md
  packages/oruga/src/components/loading/useLoadingProgrammatic.ts
  packages/oruga/src/components/modal/examples/programmatically.vue
  packages/oruga/src/components/modal/useModalProgrammatic.ts
  packages/oruga/src/components/notification/NotificationNotice.vue
  packages/oruga/src/components/notification/props.ts
  packages/oruga/src/components/notification/useNotificationProgrammatic.ts
  packages/oruga/src/components/programmatic/ProgrammaticComponent.ts
  packages/oruga/src/components/programmatic/tests/useProgrammatic.test.ts
  packages/oruga/src/components/programmatic/useProgrammatic.ts
  packages/oruga/src/components/sidebar/useSidebarProgrammatic.ts
Labels: enhancement

#1179 refactor(programmatic): rename internal property `instances` to `registry`
  packages/oruga/src/components/loading/useLoadingProgrammatic.ts
  packages/oruga/src/components/modal/useModalProgrammatic.ts
  packages/oruga/src/components/notification/useNotificationProgrammatic.ts
  packages/oruga/src/components/programmatic/ProgrammaticComponent.ts
  packages/oruga/src/components/programmatic/tests/ProgrammaticComponent.test.ts
  packages/oruga/src/components/programmatic/tests/useProgrammatic.test.ts
  packages/oruga/src/components/programmatic/useProgrammatic.ts
  packages/oruga/src/components/sidebar/useSidebarProgrammatic.ts
Labels: refactoring

#1181 test(autocomplete): add autocomplete test cases
  packages/oruga/src/components/autocomplete/Autocomplete.vue
  packages/oruga/src/components/autocomplete/examples/index.vue
  packages/oruga/src/components/autocomplete/examples/options.vue
  packages/oruga/src/components/autocomplete/examples/slots.vue
  packages/oruga/src/components/autocomplete/tests/Autocomplete.spec.cy.ts
  packages/oruga/src/components/autocomplete/tests/SimpleAutocomplete.vue
  packages/oruga/src/components/autocomplete/tests/__snapshots__/autocomplete.test.ts.snap
  packages/oruga/src/components/autocomplete/tests/autocomplete.test.ts
  packages/oruga/src/components/dropdown/tests/__snapshots__/dropdown.test.ts.snap
  packages/oruga/src/components/dropdown/tests/dropdown.axe.test.ts
  packages/oruga/src/components/dropdown/tests/dropdown.test.ts
  packages/oruga/src/components/radio/tests/radio.axe.test.ts
  packages/oruga/src/components/steps/tests/steps.axe.test.ts
  packages/oruga/src/components/switch/tests/switch.axe.test.ts
  packages/oruga/src/components/table/tests/table.axe.test.ts
  packages/oruga/src/components/table/tests/table.test.ts
  packages/oruga/src/components/tabs/tests/tabs.axe.test.ts
  packages/oruga/src/components/tabs/tests/tabs.test.ts
Labels: enhancement

#1180 feat(carousel): support w3c WAI-ARIA pattern
  packages/docs/components/Carousel.md
  packages/oruga/src/components/carousel/Carousel.vue
  packages/oruga/src/components/carousel/CarouselItem.vue
  packages/oruga/src/components/carousel/examples/base.vue
  packages/oruga/src/components/carousel/examples/index.vue
  packages/oruga/src/components/carousel/examples/indicators.vue
  packages/oruga/src/components/carousel/examples/inspector.vue
  packages/oruga/src/components/carousel/examples/list.vue
  packages/oruga/src/components/carousel/examples/readme.md
  packages/oruga/src/components/carousel/props.ts
  packages/oruga/src/components/carousel/tests/__snapshots__/carousel.test.ts.snap
  packages/oruga/src/components/carousel/tests/carousel.axe.test.ts
  packages/oruga/src/components/carousel/tests/carousel.test.ts
  packages/oruga/src/components/carousel/types.ts
  packages/oruga/src/components/dropdown/examples/index.vue
  packages/oruga/src/components/dropdown/tests/dropdown.axe.test.ts
  packages/oruga/src/components/types.ts
  packages/oruga/src/composables/useMatchMedia.ts
Labels: enhancement, a11y

#1185 feat(button): support w3c WAI-ARIA pattern
  packages/docs/components/Button.md
  packages/docs/components/Dropdown.md
  packages/oruga/src/components/button/Button.vue
  packages/oruga/src/components/button/examples/readme.md
  packages/oruga/src/components/button/props.ts
  packages/oruga/src/components/button/tests/Button.spec.cy.ts
  packages/oruga/src/components/button/tests/__snapshots__/button.test.ts.snap
  packages/oruga/src/components/checkbox/examples/readme.md
  packages/oruga/src/components/datepicker/tests/__snapshots__/datepicker.test.ts.snap
  packages/oruga/src/components/datetimepicker/tests/__snapshots__/datetimepicker.test.ts.snap
  packages/oruga/src/components/steps/tests/__snapshots__/steps.integration.test.ts.snap
  packages/oruga/src/components/steps/tests/__snapshots__/steps.test.ts.snap
  packages/oruga/src/components/types.ts
Labels: enhancement, a11y

#1186 feat(collapse): support w3c WAI-ARIA pattern
  packages/docs/components/Collapse.md
  packages/oruga/src/components/collapse/Collapse.vue
  packages/oruga/src/components/collapse/examples/accordion-buttons.vue
  packages/oruga/src/components/collapse/examples/base.vue
  packages/oruga/src/components/collapse/examples/index.vue
  packages/oruga/src/components/collapse/examples/readme.md
  packages/oruga/src/components/collapse/props.ts
  packages/oruga/src/components/collapse/tests/Collapse.spec.cy.ts
  packages/oruga/src/components/collapse/tests/SimpleCollapse.vue
  packages/oruga/src/components/collapse/tests/__snapshots__/collapse.test.ts.snap
Labels: enhancement, a11y

#1183 feat(steps): support w3c WAI-ARIA pattern
  packages/docs/components/Steps.md
  packages/oruga/src/components/steps/StepItem.vue
  packages/oruga/src/components/steps/Steps.vue
  packages/oruga/src/components/steps/examples/base.vue
  packages/oruga/src/components/steps/examples/inspector.vue
  packages/oruga/src/components/steps/props.ts
  packages/oruga/src/components/steps/tests/__snapshots__/steps.test.ts.snap
  packages/oruga/src/components/steps/tests/steps.axe.test.ts
  packages/oruga/src/components/steps/tests/steps.integration.test.ts
  packages/oruga/src/components/steps/tests/steps.test.ts
  packages/oruga/src/components/steps/types.ts
  packages/oruga/src/components/tabs/TabItem.vue
  packages/oruga/src/components/tabs/Tabs.vue
  packages/oruga/src/components/tabs/tests/__snapshots__/tabs.test.ts.snap
  packages/oruga/src/components/tabs/types.ts
  packages/oruga/src/components/types.ts
Labels: enhancement, breaking, a11y

#1184 fix: solve several a11y issues
  packages/docs/components/Carousel.md
  packages/docs/components/Datepicker.md
  packages/docs/components/Field.md
  packages/docs/components/Timepicker.md
  packages/oruga/src/components/carousel/Carousel.vue
  packages/oruga/src/components/carousel/examples/indicators.vue
  packages/oruga/src/components/carousel/examples/list.vue
  packages/oruga/src/components/carousel/examples/readme.md
  packages/oruga/src/components/checkbox/tests/checkbox.axe.test.ts
  packages/oruga/src/components/datepicker/Datepicker.vue
  packages/oruga/src/components/datepicker/examples/programmatically.vue
  packages/oruga/src/components/datepicker/examples/slots.vue
  packages/oruga/src/components/datepicker/props.ts
  packages/oruga/src/components/datepicker/tests/__snapshots__/datepicker.test.ts.snap
  packages/oruga/src/components/datetimepicker/tests/__snapshots__/datetimepicker.test.ts.snap
  packages/oruga/src/components/dropdown/Dropdown.vue
  packages/oruga/src/components/dropdown/DropdownItem.vue
  packages/oruga/src/components/dropdown/tests/__snapshots__/dropdown.test.ts.snap
  packages/oruga/src/components/field/Field.vue
  packages/oruga/src/components/field/examples/addons.vue
  packages/oruga/src/components/field/examples/base.vue
  packages/oruga/src/components/field/examples/grouped.vue
  packages/oruga/src/components/field/examples/horizontal.vue
  packages/oruga/src/components/field/examples/slots.vue
  packages/oruga/src/components/field/fieldInjection.ts
  packages/oruga/src/components/field/props.ts
  packages/oruga/src/components/menu/Menu.vue
  packages/oruga/src/components/menu/MenuItem.vue
  packages/oruga/src/components/menu/tests/menu.axe.test.ts
  packages/oruga/src/components/modal/examples/base.vue
  packages/oruga/src/components/modal/examples/programmatically.vue
  packages/oruga/src/components/radio/tests/radio.axe.test.ts
  packages/oruga/src/components/select/examples/icons.vue
  packages/oruga/src/components/select/examples/index.vue
  packages/oruga/src/components/select/examples/inspector.vue
  packages/oruga/src/components/select/examples/options-grouped.vue
  packages/oruga/src/components/slider/Slider.vue
  packages/oruga/src/components/slider/examples/inspector.vue
  packages/oruga/src/components/slider/examples/range.vue
  packages/oruga/src/components/steps/tests/__snapshots__/steps.integration.test.ts.snap
  packages/oruga/src/components/steps/tests/steps.axe.test.ts
  packages/oruga/src/components/switch/tests/switch.axe.test.ts
  packages/oruga/src/components/table/Table.vue
  packages/oruga/src/components/table/TableColumn.vue
  packages/oruga/src/components/table/tests/table.axe.test.ts
  packages/oruga/src/components/tabs/tests/tabs.axe.test.ts
  packages/oruga/src/components/timepicker/Timepicker.vue
  packages/oruga/src/components/timepicker/props.ts
  packages/oruga/src/components/timepicker/tests/__snapshots__/timepicker.test.ts.snap
  packages/oruga/src/components/types.ts
Labels: documentation, enhancement, a11y

#1188 chore: update dependencies
  package-lock.json
  package.json
  packages/docs/components/Input.md
  packages/docs/package.json
  packages/examples/package.json
  packages/oruga/package.json
  packages/oruga/src/components/datepicker/tests/datepicker.test.ts
  packages/oruga/src/components/datetimepicker/tests/datetimepicker.test.ts
Labels: dependencies

#1172 docs: scan for component default scss vars
  packages/docs/src/templates/style.ts
Labels: enhancement

#1193 feat(autocomplete): add `v-model:active` prop
  packages/docs/components/Autocomplete.md
  packages/oruga/src/components/autocomplete/Autocomplete.vue
  packages/oruga/src/components/autocomplete/props.ts
Labels: enhancement

#1196 feat(skeleton): rename classes to match pattern
  packages/oruga/src/components/skeleton/Skeleton.vue
  packages/oruga/src/components/skeleton/props.ts
  packages/oruga/src/components/types.ts
Labels: enhancement, BREAKING CHANGE

#1198 fix(tooltip): make `arrowVariantClass` class available
  packages/oruga/src/components/tooltip/Tooltip.vue
  packages/oruga/src/components/tooltip/props.ts
  packages/oruga/src/components/types.ts
Labels: bug

#1201 feat: unify HTML input based component classes
  packages/docs/components/Switch.md
  packages/oruga/src/components/autocomplete/tests/__snapshots__/autocomplete.test.ts.snap
  packages/oruga/src/components/checkbox/Checkbox.vue
  packages/oruga/src/components/checkbox/props.ts
  packages/oruga/src/components/checkbox/tests/__snapshots__/checkbox.test.ts.snap
  packages/oruga/src/components/checkbox/tests/checkbox.test.ts
  packages/oruga/src/components/datepicker/tests/__snapshots__/datepicker.test.ts.snap
  packages/oruga/src/components/datetimepicker/tests/__snapshots__/datetimepicker.test.ts.snap
  packages/oruga/src/components/field/tests/field.test.ts
  packages/oruga/src/components/input/Input.vue
  packages/oruga/src/components/input/props.ts
  packages/oruga/src/components/input/tests/__snapshots__/input.test.ts.snap
  packages/oruga/src/components/input/tests/input.test.ts
  packages/oruga/src/components/radio/Radio.vue
  packages/oruga/src/components/radio/props.ts
  packages/oruga/src/components/radio/tests/__snapshots__/radio.test.ts.snap
  packages/oruga/src/components/select/Select.vue
  packages/oruga/src/components/select/props.ts
  packages/oruga/src/components/select/tests/__snapshots__/select.test.ts.snap
  packages/oruga/src/components/select/tests/select.test.ts
  packages/oruga/src/components/switch/Switch.vue
  packages/oruga/src/components/switch/examples/readme.md
  packages/oruga/src/components/switch/props.ts
  packages/oruga/src/components/switch/tests/__snapshots__/switch.test.ts.snap
  packages/oruga/src/components/switch/tests/switch.test.ts
  packages/oruga/src/components/taginput/tests/__snapshots__/taginput.test.ts.snap
  packages/oruga/src/components/timepicker/tests/__snapshots__/timepicker.test.ts.snap
  packages/oruga/src/components/types.ts
Labels: BREAKING CHANGE, refactoring

#1200 feat(field): change prop `groupMultiline` to `multiline`
  packages/docs/components/Field.md
  packages/oruga/src/components/autocomplete/examples/selection.vue
  packages/oruga/src/components/field/Field.vue
  packages/oruga/src/components/field/examples/grouped.vue
  packages/oruga/src/components/field/props.ts
  packages/oruga/src/components/field/tests/field.test.ts
  packages/oruga/src/components/pagination/examples/base.vue
  packages/oruga/src/components/steps/examples/base.vue
  packages/oruga/src/components/table/examples/checkable.vue
  packages/oruga/src/components/table/examples/customise.vue
  packages/oruga/src/components/table/examples/detailed.vue
  packages/oruga/src/components/table/examples/pagination.vue
  packages/oruga/src/components/tabs/examples/vertical.vue
  packages/oruga/src/components/taginput/examples/autocomplete.vue
  packages/oruga/src/components/types.ts
Labels: BREAKING CHANGE, refactoring

#1207 docs: refactor inspect data action
  packages/docs/.vitepress/theme/components/InspectorWrapper.vue
  packages/docs/src/types.ts
  packages/oruga/src/components/autocomplete/examples/inspector.vue
  packages/oruga/src/components/button/examples/inspector.vue
  packages/oruga/src/components/carousel/examples/inspector.vue
  packages/oruga/src/components/checkbox/examples/inspector.vue
  packages/oruga/src/components/collapse/examples/inspector.vue
  packages/oruga/src/components/datepicker/examples/inspector.vue
  packages/oruga/src/components/datetimepicker/examples/inspector.vue
  packages/oruga/src/components/dropdown/examples/inspector.vue
  packages/oruga/src/components/field/examples/inspector.vue
  packages/oruga/src/components/icon/examples/inspector.vue
  packages/oruga/src/components/input/examples/inspector.vue
  packages/oruga/src/components/loading/examples/inspector.vue
  packages/oruga/src/components/menu/examples/inspector.vue
  packages/oruga/src/components/modal/examples/inspector.vue
  packages/oruga/src/components/notification/examples/inspector.vue
  packages/oruga/src/components/pagination/examples/inspector.vue
  packages/oruga/src/components/radio/examples/inspector.vue
  packages/oruga/src/components/select/examples/inspector.vue
  packages/oruga/src/components/sidebar/examples/inspector.vue
  packages/oruga/src/components/skeleton/examples/inspector.vue
  packages/oruga/src/components/slider/examples/inspector.vue
  packages/oruga/src/components/steps/examples/inspector.vue
  packages/oruga/src/components/switch/examples/inspector.vue
  packages/oruga/src/components/table/examples/inspector.vue
  packages/oruga/src/components/tabs/examples/inspector.vue
  packages/oruga/src/components/taginput/examples/inspector.vue
  packages/oruga/src/components/timepicker/examples/inspector.vue
  packages/oruga/src/components/tooltip/examples/inspector.vue
  packages/oruga/src/components/upload/examples/inspector.vue
Labels: documentation

#1205 feat(datepicker): unify class names & remove unnecessary classes
  packages/oruga/src/components/datepicker/Datepicker.vue
  packages/oruga/src/components/datepicker/DatepickerMonth.vue
  packages/oruga/src/components/datepicker/DatepickerTable.vue
  packages/oruga/src/components/datepicker/DatepickerTableRow.vue
  packages/oruga/src/components/datepicker/examples/inspector.vue
  packages/oruga/src/components/datepicker/props.ts
  packages/oruga/src/components/datepicker/tests/__snapshots__/datepicker.test.ts.snap
  packages/oruga/src/components/datepicker/tests/datepicker.test.ts
  packages/oruga/src/components/datetimepicker/tests/__snapshots__/datetimepicker.test.ts.snap
  packages/oruga/src/components/types.ts
Labels: BREAKING CHANGE, refactoring

#1191 chore: update dependencies | fix type problems
  package-lock.json
  package.json
  packages/docs/components/Button.md
  packages/docs/package.json
  packages/examples/package.json
  packages/oruga/package.json
  packages/oruga/src/components/carousel/Carousel.vue
  packages/oruga/src/components/datepicker/useDatepickerMixins.ts
  packages/oruga/src/components/datetimepicker/types.ts
  packages/oruga/src/components/datetimepicker/useDatetimepickerMixin.ts
  packages/oruga/src/components/timepicker/types.ts
  packages/oruga/src/components/timepicker/useTimepickerMixins.ts
Labels: dependencies

#1214 fix(menu): solve keyboard navigation issues
  packages/oruga/src/components/menu/Menu.vue
  packages/oruga/src/components/menu/MenuItem.vue
  packages/oruga/src/components/menu/examples/links.vue
Labels: bug

#1209 docs: solve issues using programmatic examples inside web component
  packages/docs/.vitepress/theme/components/ExampleShowcase.ce.vue
  packages/docs/.vitepress/theme/components/ExampleShowcase.ts
  packages/docs/.vitepress/theme/components/ThemeSelector.vue
  packages/docs/.vitepress/theme/index.ts
  packages/docs/.vitepress/theme/layout/Layout.vue
  packages/oruga/src/components/programmatic/useProgrammatic.ts
  packages/oruga/src/utils/plugins.ts
Labels: bug, documentation

#1211 fix(datetimepicker): add missing `mobileModal` and `desktopModal` props
  packages/docs/components/Datetimepicker.md
  packages/docs/components/Timepicker.md
  packages/oruga/src/components/datetimepicker/Datetimepicker.vue
  packages/oruga/src/components/datetimepicker/props.ts
  packages/oruga/src/components/timepicker/Timepicker.vue
  packages/oruga/src/components/timepicker/tests/__snapshots__/timepicker.test.ts.snap
  packages/oruga/src/components/types.ts
Labels: bug, enhancement

#1215 refacor(programmatic): add internal `container` property for programmatic components
  packages/oruga/src/components/loading/props.ts
  packages/oruga/src/components/modal/props.ts
  packages/oruga/src/components/sidebar/props.ts
Labels: refactoring
