Repository oruga-ui/oruga, pull requests merged in 2025-04, with the labels that each got.

#1277 docs: correct typo
  packages/oruga/src/components/sidebar/examples/index.vue
Labels: documentation

#1274 fix(slider): solve non-range slide is not clickable
  packages/oruga/src/components/slider/Slider.vue
Labels: bug

#1280 docs(tab): add additional examples
  packages/oruga/src/components/tabs/examples/base.vue
  packages/oruga/src/components/tabs/examples/expanded.vue
  packages/oruga/src/components/tabs/examples/long-header.vue
  packages/oruga/src/components/tabs/examples/position.vue
  packages/oruga/src/components/tabs/examples/sizes.vue
  packages/oruga/src/components/tabs/examples/types.vue
  packages/oruga/src/components/tabs/examples/vertical.vue
Labels: documentation, enhancement

#1279 fix(notification): solve programmatic does not pass variant to notification
  packages/oruga/src/components/notification/NotificationNotice.vue
  packages/oruga/src/components/notification/tests/useNotificationProgrammatic.test.ts
Labels: bug

#1283 fix(table): solve column labels are lost on mobile cards
  packages/oruga/src/components/table/Table.vue
  packages/oruga/src/components/table/tests/__snapshots__/table.test.ts.snap
Labels: bug

#1287 fix(trapFocus): add preventScroll for trapFocus first focus
  packages/oruga/src/composables/useTrapFocus.ts
Labels: bug
